# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='page_count',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.IntegerField(choices=[(1, b'Doujinshi'), (2, b'Manga'), (3, b'Game CG'), (4, b'Artist CG'), (5, b'Western'), (6, b'Non-H'), (7, b'Image Set'), (8, b'Cosplay'), (9, b'Asian Porn'), (0, b'Misc')], default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='expunged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='filecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_jpn',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='token',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
