# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'HI', b'Hard Include'), (b'SI', b'Soft Include'), (b'SE', b'Soft Exclude'), (b'HE', b'Hard Exclude')], max_length=2)),
                ('query_param', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'<built-in function id>', max_length=100)),
                ('user', models.CharField(blank=True, default=b'', max_length=100)),
                ('description', models.CharField(blank=True, default=b'', max_length=1000)),
                ('subscribed', models.BooleanField(default=False)),
                ('criteria', models.ManyToManyField(to='filters.Criteria')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
